language: node_js
node_js:
  - "4.1"

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - psql -c 'create database db_test;' -U postgres
  - "export NODE_ENV=ci-travis"
  - gulp db:migrate
  - gulp db:seed
  - gulp &
  - sleep 10

script: npm test
